spring.application.name=spring-security-LoginForm
#spring.security.user.name=kritika
#spring.security.user.password=1234


# PostgreSQL  Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.servlet.session.cookie.same-site=strict
